package springbootfromscratch.springbootfromscratch;

import com.fasterxml.jackson.databind.JsonSerializer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;


@RestController    // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @GetMapping(path="/all")
    public @ResponseBody List<User> getAllUsers() { // Iterable
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(value = "/{nachname}")
    public @ResponseBody User findByNachname (@PathVariable(value = "nachname") String nachname) {
        return userRepository.findByNachname(nachname);
    }

    // dgdfgffg
    /*
    @GetMapping(value = "/id/{id}")
    public @ResponseBody Optional<User> getUserById(@PathVariable(value = "id") Integer id) {
        return userRepository.findById(id);
    }
    */

}